sudo: required

services: docker

env:
  DOCKER_USERNAME: ryo78gs
  DOCKER_ACCESS_TOKEN: 3c9f6105-ab61-482c-baaf-6ac3c46c7244

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KET" registry.heroku.com

script:
  -docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  -docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  -docker-compose exec --env 'RAILS_ENV=test' web rails db:create

deploy:
  provider:script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  on:
    branch: master